<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AlatSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('alat')->insert([
            // ===== CGK - Terminal 1 =====
            [
                'id_lokasi' => 1,
                'id_bandara' => 1,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.01.CGK.T1.S1.BG.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Jalur Bagasi', // ⚠️ BARU
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'X-RAY',
                'nama_alat' => 'X-Ray Bagasi - Terminal 1',
                'merek' => 'Smiths Detection',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 1,
                'id_bandara' => 1,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.01.CGK.T1.S1.BG.002',
                'detail_lokasi' => 'Checkpoint Screening 1 - Jalur Cabin',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'X-RAY',
                'nama_alat' => 'X-Ray Cabin - Terminal 1',
                'merek' => 'Smiths Detection',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 1,
                'id_bandara' => 1,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.04.CGK.T1.S1.XX.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Gerbang Utama',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'WTMD',
                'nama_alat' => 'WTMD - Terminal 1',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 1,
                'id_bandara' => 1,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.10.CGK.T1.S1.XX.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Meja Petugas',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'HHMD',
                'nama_alat' => 'HHMD - Terminal 1',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 1,
                'id_bandara' => 1,
                'id_kategori' => 4,
                'kode_alat' => '14.01.01.02.CGK.T1.S1.XX.001',
                'detail_lokasi' => 'Area Check-in - Sudut Kamera 1',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'CCTV',
                'nama_alat' => 'CCTV - Terminal 1',
                'merek' => 'Hikvision',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== CGK - Terminal 2 =====
            [
                'id_lokasi' => 2,
                'id_bandara' => 1,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.01.CGK.T2.S1.BG.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Jalur Bagasi',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'X-RAY',
                'nama_alat' => 'X-Ray Bagasi - Terminal 2',
                'merek' => 'Smiths Detection',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 2,
                'id_bandara' => 1,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.01.CGK.T2.S1.BG.002',
                'detail_lokasi' => 'Checkpoint Screening 1 - Jalur Cabin',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'X-RAY',
                'nama_alat' => 'X-Ray Cabin - Terminal 2',
                'merek' => 'Smiths Detection',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 2,
                'id_bandara' => 1,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.04.CGK.T2.S1.XX.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Gerbang Utama',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'WTMD',
                'nama_alat' => 'WTMD - Terminal 2',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 2,
                'id_bandara' => 1,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.10.CGK.T2.S1.XX.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Meja Petugas',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'HHMD',
                'nama_alat' => 'HHMD - Terminal 2',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 2,
                'id_bandara' => 1,
                'id_kategori' => 4,
                'kode_alat' => '14.01.01.02.CGK.T2.S1.XX.001',
                'detail_lokasi' => 'Area Check-in - Sudut Kamera 1',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'CCTV',
                'nama_alat' => 'CCTV - Terminal 2',
                'merek' => 'Hikvision',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== CGK - Terminal 3 =====
            [
                'id_lokasi' => 3,
                'id_bandara' => 1,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.01.CGK.T3.S1.BG.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Jalur Bagasi',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'X-RAY',
                'nama_alat' => 'X-Ray Bagasi - Terminal 3',
                'merek' => 'Smiths Detection',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 3,
                'id_bandara' => 1,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.04.CGK.T3.S1.XX.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Gerbang Utama',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'WTMD',
                'nama_alat' => 'WTMD - Terminal 3',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 3,
                'id_bandara' => 1,
                'id_kategori' => 3,
                'kode_alat' => '14.01.01.03.CGK.T3.S1.XX.001',
                'detail_lokasi' => 'Ruang Mekanikal - Rooftop',
                'unit_kerja' => 'MECHANICAL FACILITY',
                'jenis_alat' => 'HVAC',
                'nama_alat' => 'HVAC - Terminal 3',
                'merek' => 'Daikin',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 3,
                'id_bandara' => 1,
                'id_kategori' => 4,
                'kode_alat' => '14.01.01.02.CGK.T3.S1.XX.001',
                'detail_lokasi' => 'Area Check-in - Sudut Kamera 1',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'CCTV',
                'nama_alat' => 'CCTV - Terminal 3',
                'merek' => 'Hikvision',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== CGK - Non Terminal =====
            [
                'id_lokasi' => 4,
                'id_bandara' => 1,
                'id_kategori' => 4,
                'kode_alat' => '14.01.01.02.CGK.NT.S1.XX.001',
                'detail_lokasi' => 'Area Parkir - Gerbang Masuk',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'CCTV',
                'nama_alat' => 'CCTV - Non Terminal',
                'merek' => 'Hikvision',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 4,
                'id_bandara' => 1,
                'id_kategori' => 3,
                'kode_alat' => '14.01.01.03.CGK.NT.S1.XX.001',
                'detail_lokasi' => 'Gedung Power House',
                'unit_kerja' => 'MECHANICAL FACILITY',
                'jenis_alat' => 'GENSET',
                'nama_alat' => 'Genset - Non Terminal',
                'merek' => 'Caterpillar',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== BDO - Terminal =====
            [
                'id_lokasi' => 5,
                'id_bandara' => 2,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.01.BDO.TL.S1.BG.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Jalur Bagasi',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'X-RAY',
                'nama_alat' => 'X-Ray Bagasi',
                'merek' => 'Smiths Detection',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 5,
                'id_bandara' => 2,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.01.BDO.TL.S1.CN.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Jalur Cabin',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'X-RAY',
                'nama_alat' => 'X-Ray Cabin',
                'merek' => 'Smiths Detection',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 5,
                'id_bandara' => 2,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.04.BDO.TL.S1.XX.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Gerbang Utama',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'WTMD',
                'nama_alat' => 'WTMD',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 5,
                'id_bandara' => 2,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.10.BDO.TL.S1.XX.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Meja Petugas',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'HHMD',
                'nama_alat' => 'HHMD',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 5,
                'id_bandara' => 2,
                'id_kategori' => 4,
                'kode_alat' => '14.01.01.02.BDO.TL.S1.XX.001',
                'detail_lokasi' => 'Area Check-in - Sudut Kamera 1',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'CCTV',
                'nama_alat' => 'CCTV',
                'merek' => 'Hikvision',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== BDO - Non Terminal =====
            [
                'id_lokasi' => 6,
                'id_bandara' => 2,
                'id_kategori' => 4,
                'kode_alat' => '14.01.01.02.BDO.NT.S1.XX.001',
                'detail_lokasi' => 'Area Parkir - Gerbang Masuk',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'CCTV',
                'nama_alat' => 'CCTV - Non Terminal',
                'merek' => 'Hikvision',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 6,
                'id_bandara' => 2,
                'id_kategori' => 3,
                'kode_alat' => '14.01.01.03.BDO.NT.S1.XX.001',
                'detail_lokasi' => 'Gedung Power House',
                'unit_kerja' => 'MECHANICAL FACILITY',
                'jenis_alat' => 'GENSET',
                'nama_alat' => 'Genset - Non Terminal',
                'merek' => 'Caterpillar',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== HLP - Terminal =====
            [
                'id_lokasi' => 7,
                'id_bandara' => 3,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.01.HLP.TL.S1.BG.002',
                'detail_lokasi' => 'Checkpoint Screening 1 - Semi BHS Batik',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'X-RAY',
                'nama_alat' => 'X-Ray Bagasi Semi BHS Batik',
                'merek' => 'Smiths Detection',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 7,
                'id_bandara' => 3,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.01.HLP.US.S1.CN.001',
                'detail_lokasi' => 'Ultimate Screening - Semi BHS Citilink',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'X-RAY',
                'nama_alat' => 'X-Ray Bagasi Semi BHS Citilink',
                'merek' => 'Smiths Detection',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 7,
                'id_bandara' => 3,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.01.HLP.TL.V0.BG.001',
                'detail_lokasi' => 'Ruang VIP - Jalur Bagasi',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'X-RAY',
                'nama_alat' => 'X-Ray Bagasi VIP (SMP)',
                'merek' => 'Smiths Detection',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 7,
                'id_bandara' => 3,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.01.HLP.IDLE.S2.CN.001',
                'detail_lokasi' => 'Checkpoint Screening 2 - Line C',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'X-RAY',
                'nama_alat' => 'X-Ray Cabin SCP2 LINE C',
                'merek' => 'Smiths Detection',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 7,
                'id_bandara' => 3,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.01.HLP.TL.S2.CN.002',
                'detail_lokasi' => 'Checkpoint Screening 2 - Line D',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'X-RAY',
                'nama_alat' => 'X-RAY Cabin SCP2 LINE D',
                'merek' => 'Smiths Detection',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 7,
                'id_bandara' => 3,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.01.HLP.TL.S3.CN.001',
                'detail_lokasi' => 'Checkpoint Screening 3 - Pintu Karyawan',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'X-RAY',
                'nama_alat' => 'X-Ray Cabin Pintu Karyawan',
                'merek' => 'Smiths Detection',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 7,
                'id_bandara' => 3,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.04.HLP.TL.S1.XX.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Line A',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'WTMD',
                'nama_alat' => 'WTMD LINE A',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 7,
                'id_bandara' => 3,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.04.HLP.TL.S1.XX.002',
                'detail_lokasi' => 'Checkpoint Screening 1 - Line B',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'WTMD',
                'nama_alat' => 'WTMD LINE B',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 7,
                'id_bandara' => 3,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.04.HLP.TL.X0.XX.002',
                'detail_lokasi' => 'Lounge Saphire - Pintu Masuk',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'WTMD',
                'nama_alat' => 'WTMD Lounge Saphire',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 7,
                'id_bandara' => 3,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.04.HLP.TL.S2.XX.001',
                'detail_lokasi' => 'Checkpoint Screening 2 - Line C',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'WTMD',
                'nama_alat' => 'WTMD Line C',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 7,
                'id_bandara' => 3,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.04.HLP.TL.S2.XX.002',
                'detail_lokasi' => 'Checkpoint Screening 2 - Line D',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'WTMD',
                'nama_alat' => 'WTMD Line D',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 7,
                'id_bandara' => 3,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.04.HLP.TL.V0.XX.001',
                'detail_lokasi' => 'Ruang VIP - Pintu Masuk',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'WTMD',
                'nama_alat' => 'WTMD VIP (SMP)',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 7,
                'id_bandara' => 3,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.10.HLP.TL.S1.XX.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Meja Petugas 1',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'HHMD',
                'nama_alat' => 'HHMD.001',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 7,
                'id_bandara' => 3,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.10.HLP.TL.S2.XX.001',
                'detail_lokasi' => 'Checkpoint Screening 2 - Meja Petugas',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'HHMD',
                'nama_alat' => 'HHMD.002',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 7,
                'id_bandara' => 3,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.10.HLP.TL.X0.XX.001',
                'detail_lokasi' => 'Lounge Saphire - Meja Petugas 1',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'HHMD',
                'nama_alat' => 'HHMD.003',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 7,
                'id_bandara' => 3,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.10.HLP.TL.X0.XX.002',
                'detail_lokasi' => 'Lounge Saphire - Meja Petugas 2',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'HHMD',
                'nama_alat' => 'HHMD.004',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 7,
                'id_bandara' => 3,
                'id_kategori' => 4,
                'kode_alat' => '14.01.01.02.HLP.TL.S1.XX.001',
                'detail_lokasi' => 'Area Check-in - Sudut Kamera 1',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'CCTV',
                'nama_alat' => 'CCTV',
                'merek' => 'Hikvision',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== HLP - Non Terminal =====
            [
                'id_lokasi' => 8,
                'id_bandara' => 3,
                'id_kategori' => 4,
                'kode_alat' => '14.01.01.02.HLP.NT.S1.XX.001',
                'detail_lokasi' => 'Area Parkir - Gerbang Masuk',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'CCTV',
                'nama_alat' => 'CCTV - Non Terminal',
                'merek' => 'Hikvision',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 8,
                'id_bandara' => 3,
                'id_kategori' => 3,
                'kode_alat' => '14.01.01.03.HLP.NT.S1.XX.001',
                'detail_lokasi' => 'Gedung Power House',
                'unit_kerja' => 'MECHANICAL FACILITY',
                'jenis_alat' => 'GENSET',
                'nama_alat' => 'Genset - Non Terminal',
                'merek' => 'Caterpillar',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== KJT - Terminal =====
            [
                'id_lokasi' => 9,
                'id_bandara' => 4,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.01.KJT.TL.S1.BG.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Jalur Bagasi',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'X-RAY',
                'nama_alat' => 'X-Ray Bagasi',
                'merek' => 'Smiths Detection',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 9,
                'id_bandara' => 4,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.01.KJT.TL.S1.CN.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Jalur Cabin',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'X-RAY',
                'nama_alat' => 'X-Ray Cabin',
                'merek' => 'Smiths Detection',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 9,
                'id_bandara' => 4,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.04.KJT.TL.S1.XX.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Gerbang Utama',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'WTMD',
                'nama_alat' => 'WTMD',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 9,
                'id_bandara' => 4,
                'id_kategori' => 1,
                'kode_alat' => '14.01.01.10.KJT.TL.S1.XX.001',
                'detail_lokasi' => 'Checkpoint Screening 1 - Meja Petugas',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'HHMD',
                'nama_alat' => 'HHMD',
                'merek' => 'Garrett',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 9,
                'id_bandara' => 4,
                'id_kategori' => 4,
                'kode_alat' => '14.01.01.02.KJT.TL.S1.XX.001',
                'detail_lokasi' => 'Area Check-in - Sudut Kamera 1',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'CCTV',
                'nama_alat' => 'CCTV',
                'merek' => 'Hikvision',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== KJT - Non Terminal =====
            [
                'id_lokasi' => 10,
                'id_bandara' => 4,
                'id_kategori' => 4,
                'kode_alat' => '14.01.01.02.KJT.NT.S1.XX.001',
                'detail_lokasi' => 'Area Parkir - Gerbang Masuk',
                'unit_kerja' => 'ELECTRONIC FACILITY & IT',
                'jenis_alat' => 'CCTV',
                'nama_alat' => 'CCTV - Non Terminal',
                'merek' => 'Hikvision',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_lokasi' => 10,
                'id_bandara' => 4,
                'id_kategori' => 3,
                'kode_alat' => '14.01.01.03.KJT.NT.S1.XX.001',
                'detail_lokasi' => 'Gedung Power House',
                'unit_kerja' => 'MECHANICAL FACILITY',
                'jenis_alat' => 'GENSET',
                'nama_alat' => 'Genset - Non Terminal',
                'merek' => 'Caterpillar',
                'status' => 'Aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}